import type { HorizonSystem, Palette } from '@/lib/types'

function palToTs(pal: Palette, indent: string): string {
  const rows = Object.entries(pal)
    .map(([k, v]) => `${indent}  '${k}': '${v}',`)
    .join('\n')
  return `{\n${rows}\n${indent}}`
}

export function systemToTailwind(system: HorizonSystem): string {
  const c = system.colors
  const sem = c.semantic
  const font = system.typography?.fontFamily ?? 'Inter'
  const mono = system.typography?.fontFamilyMono ?? 'monospace'
  const radius = system.radius
  const shadows = system.shadows ?? []

  const spacing = (system.spacing?.scale ?? [])
    .map((v, i) => `        '${i + 1}': '${v}px',`)
    .join('\n')
  const shadowRows = shadows
    .map((s) => `        '${s.name}': '${s.value}',`)
    .join('\n')

  return `import type { Config } from 'tailwindcss'

// Generated by Horizon — design tokens for "${system.name}".
const config: Config = {
  content: ['./src/**/*.{ts,tsx,js,jsx,html}'],
  theme: {
    extend: {
      colors: {
        primary: ${palToTs(c.primary, '        ')},
        secondary: ${palToTs(c.secondary, '        ')},
        neutral: ${palToTs(c.neutral, '        ')},
        success: '${sem.success}',
        warning: '${sem.warning}',
        error: '${sem.error}',
        info: '${sem.info}',
      },
      fontFamily: {
        sans: ['${font}', 'system-ui', 'sans-serif'],
        mono: ['${mono}', 'monospace'],
      },
      spacing: {
${spacing}
      },
      borderRadius: {
        sm: '${radius.sm}',
        md: '${radius.md}',
        lg: '${radius.lg}',
        full: '${radius.full}',
      },
      boxShadow: {
${shadowRows}
      },
    },
  },
  plugins: [],
}

export default config
`
}
